[2025-05-10T09:48:48.118+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:48:48.119+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T09:48:48.122+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:48:48.122+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:48:48.192+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:48:48.176+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T09:48:48.193+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:48:48.358+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.251 seconds
[2025-05-10T09:49:18.880+0000] {processor.py:186} INFO - Started process (PID=200) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:49:18.881+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T09:49:18.885+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:49:18.885+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:49:18.904+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:49:18.900+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T09:49:18.905+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:49:18.953+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.083 seconds
[2025-05-10T09:49:49.799+0000] {processor.py:186} INFO - Started process (PID=211) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:49:50.139+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T09:49:50.144+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:49:50.143+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:49:50.163+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:49:50.159+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T09:49:50.164+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:49:50.329+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.540 seconds
[2025-05-10T09:50:20.739+0000] {processor.py:186} INFO - Started process (PID=223) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:50:20.743+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T09:50:20.748+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:50:20.747+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:50:20.769+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:50:20.764+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T09:50:20.770+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:50:20.901+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.172 seconds
[2025-05-10T09:50:51.591+0000] {processor.py:186} INFO - Started process (PID=235) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:50:51.593+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T09:50:51.596+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:50:51.596+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:50:51.662+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:50:51.658+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T09:50:51.663+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:50:51.820+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.239 seconds
[2025-05-10T09:51:22.656+0000] {processor.py:186} INFO - Started process (PID=246) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:51:22.658+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T09:51:22.663+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:51:22.662+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:51:22.683+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:51:22.679+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T09:51:22.684+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:51:22.844+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.198 seconds
[2025-05-10T09:51:54.332+0000] {processor.py:186} INFO - Started process (PID=256) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:51:54.334+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T09:51:54.339+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:51:54.338+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:51:54.358+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:51:54.354+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T09:51:54.359+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:51:54.409+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.087 seconds
[2025-05-10T09:52:25.574+0000] {processor.py:186} INFO - Started process (PID=267) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:52:25.971+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T09:52:25.977+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:52:25.976+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:52:25.998+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:52:25.994+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T09:52:26.000+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:52:26.268+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.747 seconds
[2025-05-10T09:52:56.408+0000] {processor.py:186} INFO - Started process (PID=278) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:52:56.409+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T09:52:56.414+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:52:56.413+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:52:56.468+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:52:56.464+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T09:52:56.470+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:52:56.675+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.310 seconds
[2025-05-10T09:53:27.433+0000] {processor.py:186} INFO - Started process (PID=289) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:53:27.435+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T09:53:27.439+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:53:27.439+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:53:27.458+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:53:27.454+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T09:53:27.459+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:53:27.507+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.084 seconds
[2025-05-10T09:53:57.722+0000] {processor.py:186} INFO - Started process (PID=300) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:53:57.723+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T09:53:57.730+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:53:57.729+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:53:57.755+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:53:57.749+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T09:53:57.757+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:53:57.814+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.112 seconds
[2025-05-10T09:54:28.711+0000] {processor.py:186} INFO - Started process (PID=311) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:54:28.713+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T09:54:28.720+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:54:28.719+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:54:28.746+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:54:28.739+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T09:54:28.747+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:54:28.798+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.099 seconds
[2025-05-10T09:54:59.686+0000] {processor.py:186} INFO - Started process (PID=322) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:54:59.689+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T09:54:59.696+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:54:59.695+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:54:59.723+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:54:59.716+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T09:54:59.725+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:54:59.791+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.117 seconds
[2025-05-10T09:55:30.589+0000] {processor.py:186} INFO - Started process (PID=332) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:55:30.592+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T09:55:30.597+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:55:30.596+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:55:30.618+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:55:30.613+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T09:55:30.620+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:55:30.676+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.096 seconds
[2025-05-10T09:56:01.761+0000] {processor.py:186} INFO - Started process (PID=343) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:56:01.762+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T09:56:01.767+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:56:01.766+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:56:01.785+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:56:01.781+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T09:56:01.787+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:56:01.838+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.088 seconds
[2025-05-10T09:56:32.401+0000] {processor.py:186} INFO - Started process (PID=354) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:56:32.403+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T09:56:32.408+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:56:32.407+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:56:32.427+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:56:32.423+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T09:56:32.428+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:56:32.482+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.092 seconds
[2025-05-10T09:57:03.058+0000] {processor.py:186} INFO - Started process (PID=365) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:57:03.059+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T09:57:03.065+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:57:03.064+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:57:03.085+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:57:03.080+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T09:57:03.086+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:57:03.138+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.091 seconds
[2025-05-10T09:57:33.483+0000] {processor.py:186} INFO - Started process (PID=376) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:57:33.488+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T09:57:33.494+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:57:33.493+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:57:33.517+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:57:33.513+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T09:57:33.518+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:57:33.568+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.099 seconds
[2025-05-10T09:58:04.774+0000] {processor.py:186} INFO - Started process (PID=388) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:58:04.788+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T09:58:04.793+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:58:04.792+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:58:04.830+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:58:04.823+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T09:58:04.832+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:58:04.953+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.191 seconds
[2025-05-10T09:58:35.361+0000] {processor.py:186} INFO - Started process (PID=398) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:58:35.363+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T09:58:35.370+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:58:35.369+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:58:35.401+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:58:35.394+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T09:58:35.403+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:58:35.457+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.112 seconds
[2025-05-10T09:59:06.642+0000] {processor.py:186} INFO - Started process (PID=409) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:59:06.706+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T09:59:06.802+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:59:06.800+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:59:06.868+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:59:06.857+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T09:59:06.870+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:59:07.124+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.610 seconds
[2025-05-10T09:59:37.464+0000] {processor.py:186} INFO - Started process (PID=420) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:59:37.465+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T09:59:37.470+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:59:37.470+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:59:37.491+0000] {logging_mixin.py:190} INFO - [2025-05-10T09:59:37.486+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T09:59:37.492+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T09:59:37.556+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.106 seconds
[2025-05-10T10:00:08.005+0000] {processor.py:186} INFO - Started process (PID=430) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T10:00:08.011+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T10:00:08.017+0000] {logging_mixin.py:190} INFO - [2025-05-10T10:00:08.016+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T10:00:08.041+0000] {logging_mixin.py:190} INFO - [2025-05-10T10:00:08.036+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T10:00:08.043+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T10:00:08.125+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.133 seconds
[2025-05-10T10:00:38.586+0000] {processor.py:186} INFO - Started process (PID=441) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T10:00:38.589+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T10:00:38.593+0000] {logging_mixin.py:190} INFO - [2025-05-10T10:00:38.592+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T10:00:38.614+0000] {logging_mixin.py:190} INFO - [2025-05-10T10:00:38.610+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T10:00:38.616+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T10:00:38.784+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.214 seconds
[2025-05-10T10:46:19.410+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T10:46:19.453+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T10:46:19.790+0000] {logging_mixin.py:190} INFO - [2025-05-10T10:46:19.785+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T10:46:20.608+0000] {logging_mixin.py:190} INFO - [2025-05-10T10:46:20.098+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T10:46:20.624+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T10:46:21.955+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 2.625 seconds
[2025-05-10T10:46:53.589+0000] {processor.py:186} INFO - Started process (PID=200) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T10:46:53.679+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T10:46:53.685+0000] {logging_mixin.py:190} INFO - [2025-05-10T10:46:53.684+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T10:46:53.723+0000] {logging_mixin.py:190} INFO - [2025-05-10T10:46:53.714+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T10:46:53.725+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T10:46:54.134+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.572 seconds
[2025-05-10T10:47:25.502+0000] {processor.py:186} INFO - Started process (PID=210) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T10:47:25.506+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T10:47:25.511+0000] {logging_mixin.py:190} INFO - [2025-05-10T10:47:25.510+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T10:47:25.539+0000] {logging_mixin.py:190} INFO - [2025-05-10T10:47:25.531+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T10:47:25.540+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T10:47:26.073+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.587 seconds
[2025-05-10T10:47:57.507+0000] {processor.py:186} INFO - Started process (PID=221) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T10:47:57.511+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T10:47:57.516+0000] {logging_mixin.py:190} INFO - [2025-05-10T10:47:57.515+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T10:47:57.544+0000] {logging_mixin.py:190} INFO - [2025-05-10T10:47:57.536+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T10:47:57.546+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T10:47:57.888+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.392 seconds
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       [2025-05-10T11:21:59.185+0000] {processor.py:186} INFO - Started process (PID=191) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T11:21:59.253+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T11:21:59.257+0000] {logging_mixin.py:190} INFO - [2025-05-10T11:21:59.256+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T11:21:59.297+0000] {logging_mixin.py:190} INFO - [2025-05-10T11:21:59.281+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T11:21:59.299+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T11:21:59.366+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.230 seconds
[2025-05-10T11:22:29.914+0000] {processor.py:186} INFO - Started process (PID=202) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T11:22:29.939+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T11:22:29.966+0000] {logging_mixin.py:190} INFO - [2025-05-10T11:22:29.964+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T11:22:30.040+0000] {logging_mixin.py:190} INFO - [2025-05-10T11:22:30.028+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T11:22:30.043+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T11:22:30.267+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.400 seconds
[2025-05-10T11:23:02.117+0000] {processor.py:186} INFO - Started process (PID=213) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T11:23:02.120+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T11:23:02.127+0000] {logging_mixin.py:190} INFO - [2025-05-10T11:23:02.126+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T11:23:02.164+0000] {logging_mixin.py:190} INFO - [2025-05-10T11:23:02.156+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T11:23:02.167+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T11:23:02.257+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.161 seconds
[2025-05-10T16:58:23.161+0000] {processor.py:186} INFO - Started process (PID=195) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T16:58:23.165+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T16:58:23.170+0000] {logging_mixin.py:190} INFO - [2025-05-10T16:58:23.170+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T16:58:23.211+0000] {logging_mixin.py:190} INFO - [2025-05-10T16:58:23.194+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T16:58:23.213+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T16:58:23.389+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.239 seconds
[2025-05-10T16:58:53.862+0000] {processor.py:186} INFO - Started process (PID=206) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T16:58:53.863+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T16:58:53.869+0000] {logging_mixin.py:190} INFO - [2025-05-10T16:58:53.868+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T16:58:53.897+0000] {logging_mixin.py:190} INFO - [2025-05-10T16:58:53.889+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T16:58:53.902+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T16:58:53.985+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.140 seconds
[2025-05-10T16:59:25.005+0000] {processor.py:186} INFO - Started process (PID=217) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T16:59:25.010+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T16:59:25.026+0000] {logging_mixin.py:190} INFO - [2025-05-10T16:59:25.024+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T16:59:25.091+0000] {logging_mixin.py:190} INFO - [2025-05-10T16:59:25.078+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T16:59:25.093+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T16:59:25.419+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.453 seconds
[2025-05-10T16:59:55.570+0000] {processor.py:186} INFO - Started process (PID=227) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T16:59:55.572+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T16:59:55.576+0000] {logging_mixin.py:190} INFO - [2025-05-10T16:59:55.575+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T16:59:55.596+0000] {logging_mixin.py:190} INFO - [2025-05-10T16:59:55.592+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T16:59:55.598+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T16:59:55.657+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.101 seconds
[2025-05-10T17:00:26.473+0000] {processor.py:186} INFO - Started process (PID=238) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:00:26.475+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:00:26.481+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:00:26.480+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:00:26.515+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:00:26.509+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:00:26.517+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:00:26.596+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.137 seconds
[2025-05-10T17:00:57.757+0000] {processor.py:186} INFO - Started process (PID=249) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:00:57.833+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:00:57.841+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:00:57.840+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:00:57.864+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:00:57.858+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:00:57.866+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:00:57.959+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.216 seconds
[2025-05-10T17:01:28.712+0000] {processor.py:186} INFO - Started process (PID=260) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:01:28.839+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:01:29.223+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:01:29.220+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:01:29.341+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:01:29.337+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:01:29.419+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:01:30.665+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 1.978 seconds
[2025-05-10T17:02:02.173+0000] {processor.py:186} INFO - Started process (PID=271) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:02:02.263+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:02:02.270+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:02:02.269+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:02:02.415+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:02:02.295+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:02:02.417+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:02:03.254+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 1.096 seconds
[2025-05-10T17:02:33.894+0000] {processor.py:186} INFO - Started process (PID=281) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:02:33.898+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:02:33.927+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:02:33.926+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:02:34.100+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:02:34.081+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:02:34.115+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:02:35.262+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 1.380 seconds
[2025-05-10T17:03:08.344+0000] {processor.py:186} INFO - Started process (PID=292) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:03:08.441+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:03:08.478+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:03:08.477+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:03:08.547+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:03:08.540+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:03:08.549+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:03:10.573+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 2.311 seconds
[2025-05-10T17:03:41.544+0000] {processor.py:186} INFO - Started process (PID=302) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:03:41.601+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:03:41.628+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:03:41.627+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:03:41.752+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:03:41.648+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:03:41.753+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:03:41.961+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.432 seconds
[2025-05-10T17:04:14.454+0000] {processor.py:186} INFO - Started process (PID=313) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:04:14.458+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:04:14.554+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:04:14.553+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:04:14.708+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:04:14.701+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:04:14.710+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:04:15.717+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 1.747 seconds
[2025-05-10T17:04:46.905+0000] {processor.py:186} INFO - Started process (PID=324) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:04:46.928+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:04:46.935+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:04:46.935+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:04:47.082+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:04:47.075+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:04:47.085+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:04:47.272+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.433 seconds
[2025-05-10T17:05:17.619+0000] {processor.py:186} INFO - Started process (PID=334) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:05:17.629+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:05:17.668+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:05:17.667+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:05:17.878+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:05:17.783+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:05:18.015+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:05:18.942+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 1.347 seconds
[2025-05-10T17:05:49.909+0000] {processor.py:186} INFO - Started process (PID=344) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:05:49.911+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:05:49.917+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:05:49.916+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:05:49.973+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:05:49.954+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:05:50.093+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:05:51.486+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 1.701 seconds
[2025-05-10T17:06:22.504+0000] {processor.py:186} INFO - Started process (PID=355) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:06:22.507+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:06:22.513+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:06:22.512+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:06:22.568+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:06:22.560+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:06:22.571+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:06:23.222+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.734 seconds
[2025-05-10T17:06:53.672+0000] {processor.py:186} INFO - Started process (PID=366) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:06:53.735+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:06:53.744+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:06:53.743+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:06:53.829+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:06:53.765+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:06:53.832+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:06:54.574+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.938 seconds
[2025-05-10T17:07:25.492+0000] {processor.py:186} INFO - Started process (PID=377) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:07:25.511+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:07:25.522+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:07:25.522+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:07:25.596+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:07:25.588+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:07:25.605+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:07:26.126+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.723 seconds
[2025-05-10T17:07:57.452+0000] {processor.py:186} INFO - Started process (PID=388) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:07:57.454+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:07:57.476+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:07:57.475+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:07:57.577+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:07:57.569+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:07:57.581+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:07:58.854+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 1.434 seconds
[2025-05-10T17:08:30.611+0000] {processor.py:186} INFO - Started process (PID=398) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:08:30.613+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:08:30.621+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:08:30.620+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:08:30.652+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:08:30.646+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:08:30.654+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:08:30.731+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.134 seconds
[2025-05-10T17:09:01.668+0000] {processor.py:186} INFO - Started process (PID=409) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:09:01.670+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:09:01.675+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:09:01.674+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:09:01.756+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:09:01.751+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:09:01.757+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:09:02.975+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 1.322 seconds
[2025-05-10T17:09:33.786+0000] {processor.py:186} INFO - Started process (PID=420) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:09:33.788+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:09:33.800+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:09:33.799+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:09:33.830+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:09:33.822+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:09:33.832+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:09:33.891+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.129 seconds
[2025-05-10T17:10:04.985+0000] {processor.py:186} INFO - Started process (PID=432) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:10:04.989+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:10:04.994+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:10:04.994+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:10:05.020+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:10:05.015+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:10:05.041+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:10:05.197+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.231 seconds
[2025-05-10T17:10:36.283+0000] {processor.py:186} INFO - Started process (PID=443) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:10:36.284+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:10:36.290+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:10:36.289+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:10:36.355+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:10:36.348+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:10:36.358+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:10:37.045+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.775 seconds
[2025-05-10T17:11:08.351+0000] {processor.py:186} INFO - Started process (PID=454) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:11:08.357+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:11:08.364+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:11:08.363+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:11:08.391+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:11:08.385+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:11:08.393+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:11:08.844+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.504 seconds
[2025-05-10T17:11:39.972+0000] {processor.py:186} INFO - Started process (PID=465) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:11:39.974+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:11:39.978+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:11:39.977+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:11:40.000+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:11:39.995+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:11:40.002+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:11:40.592+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.678 seconds
[2025-05-10T17:12:11.241+0000] {processor.py:186} INFO - Started process (PID=476) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:12:11.242+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:12:11.247+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:12:11.246+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:12:11.271+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:12:11.266+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:12:11.272+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:12:11.325+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.096 seconds
[2025-05-10T17:12:42.540+0000] {processor.py:186} INFO - Started process (PID=486) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:12:42.544+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:12:42.551+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:12:42.551+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:12:42.575+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:12:42.570+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:12:42.577+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:12:42.892+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.368 seconds
[2025-05-10T17:13:14.382+0000] {processor.py:186} INFO - Started process (PID=498) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:13:14.401+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:13:14.420+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:13:14.419+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:13:14.455+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:13:14.447+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:13:14.459+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:13:16.057+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 1.688 seconds
[2025-05-10T17:13:47.308+0000] {processor.py:186} INFO - Started process (PID=509) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:13:47.309+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:13:47.314+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:13:47.313+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:13:47.337+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:13:47.332+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:13:47.338+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:13:47.718+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.424 seconds
[2025-05-10T17:14:18.778+0000] {processor.py:186} INFO - Started process (PID=521) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:14:18.783+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:14:18.788+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:14:18.787+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:14:18.811+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:14:18.806+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:14:18.812+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:14:18.868+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.105 seconds
[2025-05-10T17:14:49.246+0000] {processor.py:186} INFO - Started process (PID=532) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:14:49.251+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:14:49.264+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:14:49.260+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:14:49.314+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:14:49.306+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:14:49.316+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:14:49.610+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.378 seconds
[2025-05-10T17:15:19.935+0000] {processor.py:186} INFO - Started process (PID=542) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:15:19.938+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:15:19.950+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:15:19.948+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:15:19.999+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:15:19.987+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:15:20.003+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:15:20.303+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.394 seconds
[2025-05-10T17:15:51.089+0000] {processor.py:186} INFO - Started process (PID=554) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:15:51.099+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:15:51.116+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:15:51.110+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:15:51.233+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:15:51.173+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:15:51.242+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:15:51.384+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.326 seconds
[2025-05-10T17:16:23.140+0000] {processor.py:186} INFO - Started process (PID=566) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:16:23.143+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:16:23.167+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:16:23.166+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:16:23.674+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:16:23.546+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:16:23.675+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:16:23.762+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.665 seconds
[2025-05-10T17:16:54.492+0000] {processor.py:186} INFO - Started process (PID=576) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:16:54.497+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:16:54.512+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:16:54.504+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:16:54.681+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:16:54.669+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:16:54.683+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:16:54.953+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.478 seconds
[2025-05-10T17:17:25.585+0000] {processor.py:186} INFO - Started process (PID=586) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:17:25.587+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:17:25.595+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:17:25.594+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:17:25.654+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:17:25.649+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:17:25.656+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:17:26.141+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.571 seconds
[2025-05-10T17:17:56.853+0000] {processor.py:186} INFO - Started process (PID=596) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:17:56.856+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:17:56.862+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:17:56.861+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:17:56.886+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:17:56.881+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:17:56.887+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:17:57.027+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.184 seconds
[2025-05-10T17:18:28.334+0000] {processor.py:186} INFO - Started process (PID=607) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:18:28.335+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:18:28.340+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:18:28.339+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:18:28.378+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:18:28.356+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:18:28.380+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:18:28.479+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.163 seconds
[2025-05-10T17:18:59.229+0000] {processor.py:186} INFO - Started process (PID=617) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:18:59.232+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:18:59.236+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:18:59.236+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:18:59.266+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:18:59.263+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:18:59.267+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:18:59.454+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.232 seconds
[2025-05-10T17:19:30.519+0000] {processor.py:186} INFO - Started process (PID=628) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:19:30.520+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:19:30.526+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:19:30.524+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:19:30.557+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:19:30.551+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:19:30.558+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:19:30.647+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.141 seconds
[2025-05-10T17:20:01.093+0000] {processor.py:186} INFO - Started process (PID=639) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:20:01.095+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:20:01.099+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:20:01.098+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:20:01.118+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:20:01.113+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:20:01.120+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:20:01.159+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.075 seconds
[2025-05-10T17:20:32.264+0000] {processor.py:186} INFO - Started process (PID=650) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:20:32.266+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:20:32.270+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:20:32.269+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:20:32.286+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:20:32.283+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:20:32.287+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:20:32.354+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.100 seconds
[2025-05-10T17:21:03.485+0000] {processor.py:186} INFO - Started process (PID=661) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:21:03.487+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:21:03.492+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:21:03.491+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:21:03.517+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:21:03.511+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:21:03.519+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:21:03.579+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.109 seconds
[2025-05-10T17:21:33.830+0000] {processor.py:186} INFO - Started process (PID=672) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:21:33.833+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:21:33.839+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:21:33.838+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:21:33.862+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:21:33.857+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:21:33.864+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:21:34.351+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.534 seconds
[2025-05-10T17:22:05.493+0000] {processor.py:186} INFO - Started process (PID=683) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:22:05.494+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:22:05.497+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:22:05.497+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:22:05.513+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:22:05.510+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:22:05.514+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:22:05.559+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.075 seconds
[2025-05-10T17:22:36.678+0000] {processor.py:186} INFO - Started process (PID=694) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:22:36.695+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:22:36.708+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:22:36.707+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:22:36.898+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:22:36.892+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:22:36.900+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:22:37.150+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.491 seconds
[2025-05-10T17:23:07.463+0000] {processor.py:186} INFO - Started process (PID=704) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:23:07.464+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:23:07.468+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:23:07.467+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:23:07.486+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:23:07.482+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:23:07.487+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:23:07.597+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.143 seconds
[2025-05-10T17:23:38.428+0000] {processor.py:186} INFO - Started process (PID=715) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:23:38.434+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:23:38.440+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:23:38.440+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:23:38.476+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:23:38.464+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:23:38.477+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:23:38.520+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.104 seconds
[2025-05-10T17:24:09.484+0000] {processor.py:186} INFO - Started process (PID=726) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:24:09.514+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:24:09.517+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:24:09.517+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:24:09.533+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:24:09.529+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:24:09.534+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:24:09.627+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.152 seconds
[2025-05-10T17:24:40.448+0000] {processor.py:186} INFO - Started process (PID=738) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:24:40.449+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:24:40.453+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:24:40.452+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:24:40.477+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:24:40.471+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:24:40.478+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:24:40.569+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.132 seconds
[2025-05-10T17:25:10.813+0000] {processor.py:186} INFO - Started process (PID=749) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:25:10.815+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:25:10.820+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:25:10.819+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:25:10.840+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:25:10.835+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:25:10.841+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:25:11.392+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.590 seconds
[2025-05-10T17:25:41.539+0000] {processor.py:186} INFO - Started process (PID=760) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:25:41.542+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:25:41.550+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:25:41.550+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:25:41.577+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:25:41.572+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:25:41.578+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:25:41.635+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.114 seconds
[2025-05-10T17:26:12.303+0000] {processor.py:186} INFO - Started process (PID=771) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:26:12.307+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:26:12.310+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:26:12.310+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:26:12.326+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:26:12.321+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:26:12.328+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:26:12.374+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.082 seconds
[2025-05-10T17:26:43.100+0000] {processor.py:186} INFO - Started process (PID=782) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:26:43.102+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:26:43.106+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:26:43.106+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:26:43.122+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:26:43.119+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:26:43.124+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:26:43.164+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.072 seconds
[2025-05-10T17:27:13.370+0000] {processor.py:186} INFO - Started process (PID=793) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:27:13.371+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-10T17:27:13.374+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:27:13.373+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:27:13.387+0000] {logging_mixin.py:190} INFO - [2025-05-10T17:27:13.384+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-10T17:27:13.388+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-10T17:27:13.422+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.062 seconds
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       