[2025-05-12T08:19:36.536+0000] {processor.py:186} INFO - Started process (PID=197) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:19:36.538+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:19:36.547+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:19:36.545+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:19:36.843+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:19:36.798+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:19:36.845+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:19:36.952+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.451 seconds
[2025-05-12T08:20:08.862+0000] {processor.py:186} INFO - Started process (PID=208) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:20:08.866+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:20:08.871+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:20:08.870+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:20:08.895+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:20:08.888+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:20:08.897+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:20:08.976+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.127 seconds
[2025-05-12T08:20:39.785+0000] {processor.py:186} INFO - Started process (PID=218) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:20:39.787+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:20:39.793+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:20:39.792+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:20:39.824+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:20:39.815+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:20:39.827+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:20:39.908+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.136 seconds
[2025-05-12T08:21:10.568+0000] {processor.py:186} INFO - Started process (PID=229) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:21:10.571+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:21:10.576+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:21:10.575+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:21:10.599+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:21:10.593+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:21:10.600+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:21:10.806+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.349 seconds
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       [2025-05-12T08:32:29.951+0000] {processor.py:186} INFO - Started process (PID=197) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:32:29.977+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:32:30.000+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:32:29.998+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:32:30.651+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:32:30.243+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:32:30.653+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:32:30.878+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 1.327 seconds
[2025-05-12T08:33:01.522+0000] {processor.py:186} INFO - Started process (PID=207) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:33:01.531+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:33:01.537+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:33:01.536+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:33:01.558+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:33:01.554+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:33:01.560+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:33:01.760+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.249 seconds
[2025-05-12T08:33:32.297+0000] {processor.py:186} INFO - Started process (PID=218) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:33:32.302+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:33:32.307+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:33:32.307+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:33:32.337+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:33:32.331+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:33:32.338+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:33:32.694+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.412 seconds
[2025-05-12T08:34:03.172+0000] {processor.py:186} INFO - Started process (PID=229) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:34:03.174+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:34:03.180+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:34:03.179+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:34:03.202+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:34:03.197+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:34:03.219+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:34:03.859+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.760 seconds
[2025-05-12T08:34:34.629+0000] {processor.py:186} INFO - Started process (PID=240) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:34:34.658+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:34:34.665+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:34:34.664+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:34:34.689+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:34:34.684+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:34:34.690+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:34:34.979+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.362 seconds
[2025-05-12T08:35:06.071+0000] {processor.py:186} INFO - Started process (PID=251) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:35:06.074+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:35:06.081+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:35:06.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:35:06.129+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:35:06.123+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:35:06.131+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:35:06.256+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.200 seconds
[2025-05-12T08:35:37.125+0000] {processor.py:186} INFO - Started process (PID=262) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:35:37.126+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:35:37.131+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:35:37.130+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:35:37.151+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:35:37.147+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:35:37.153+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:35:37.449+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.335 seconds
[2025-05-12T08:36:08.795+0000] {processor.py:186} INFO - Started process (PID=273) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:36:08.816+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:36:08.825+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:36:08.824+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:36:08.856+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:36:08.850+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:36:08.857+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:36:09.595+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.819 seconds
[2025-05-12T08:36:40.778+0000] {processor.py:186} INFO - Started process (PID=283) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:36:40.787+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:36:40.804+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:36:40.804+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:36:40.824+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:36:40.820+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:36:40.825+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:36:41.035+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.273 seconds
[2025-05-12T08:37:12.278+0000] {processor.py:186} INFO - Started process (PID=293) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:37:12.280+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:37:12.286+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:37:12.285+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:37:12.330+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:37:12.306+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:37:12.332+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:37:12.996+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.731 seconds
[2025-05-12T08:37:44.281+0000] {processor.py:186} INFO - Started process (PID=310) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:37:44.341+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:37:44.348+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:37:44.347+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:37:44.442+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:37:44.435+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:37:44.445+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:37:44.543+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.346 seconds
[2025-05-12T08:38:15.677+0000] {processor.py:186} INFO - Started process (PID=320) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:38:15.678+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:38:15.683+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:38:15.683+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:38:15.704+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:38:15.700+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:38:15.706+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:38:15.808+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.158 seconds
[2025-05-12T08:38:46.520+0000] {processor.py:186} INFO - Started process (PID=331) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:38:46.614+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:38:46.633+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:38:46.631+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:38:46.663+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:38:46.656+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:38:46.664+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:38:47.112+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.606 seconds
[2025-05-12T08:39:17.428+0000] {processor.py:186} INFO - Started process (PID=342) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:39:17.432+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:39:17.437+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:39:17.437+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:39:17.480+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:39:17.455+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:39:17.482+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:39:17.583+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.260 seconds
[2025-05-12T08:39:48.214+0000] {processor.py:186} INFO - Started process (PID=347) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:39:48.227+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:39:48.233+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:39:48.232+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:39:48.260+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:39:48.254+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:39:48.262+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:39:49.215+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 1.229 seconds
[2025-05-12T08:40:19.740+0000] {processor.py:186} INFO - Started process (PID=364) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:40:19.742+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:40:19.748+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:40:19.747+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:40:19.774+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:40:19.769+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:40:19.775+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:40:20.673+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.946 seconds
[2025-05-12T08:40:51.533+0000] {processor.py:186} INFO - Started process (PID=374) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:40:51.569+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:40:51.574+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:40:51.574+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:40:51.595+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:40:51.590+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:40:51.596+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:40:51.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.146 seconds
[2025-05-12T08:41:21.859+0000] {processor.py:186} INFO - Started process (PID=379) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:41:21.864+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:41:21.871+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:41:21.870+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:41:21.935+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:41:21.930+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:41:21.936+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:41:22.102+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.297 seconds
[2025-05-12T08:41:52.859+0000] {processor.py:186} INFO - Started process (PID=389) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:41:52.861+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:41:52.866+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:41:52.865+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:41:52.896+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:41:52.889+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:41:52.898+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:41:53.056+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.233 seconds
[2025-05-12T08:42:23.816+0000] {processor.py:186} INFO - Started process (PID=400) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:42:23.822+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:42:23.828+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:42:23.827+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:42:23.875+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:42:23.868+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:42:23.876+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:42:23.939+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.139 seconds
[2025-05-12T08:42:54.347+0000] {processor.py:186} INFO - Started process (PID=411) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:42:54.349+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:42:54.361+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:42:54.360+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:42:54.384+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:42:54.379+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:42:54.385+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:42:54.473+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.137 seconds
[2025-05-12T08:43:25.963+0000] {processor.py:186} INFO - Started process (PID=428) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:43:25.966+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:43:25.972+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:43:25.971+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:43:25.998+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:43:25.992+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:43:25.999+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:43:26.072+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.123 seconds
[2025-05-12T08:43:57.890+0000] {processor.py:186} INFO - Started process (PID=439) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:43:57.892+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:43:57.901+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:43:57.900+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:43:57.971+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:43:57.937+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:43:57.975+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:43:58.091+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.238 seconds
[2025-05-12T08:44:29.310+0000] {processor.py:186} INFO - Started process (PID=449) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:44:29.315+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:44:29.321+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:44:29.320+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:44:29.365+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:44:29.360+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:44:29.366+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:44:29.487+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.190 seconds
[2025-05-12T08:45:00.387+0000] {processor.py:186} INFO - Started process (PID=460) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:45:00.389+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:45:00.395+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:45:00.394+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:45:00.419+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:45:00.414+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:45:00.420+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:45:00.488+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.115 seconds
[2025-05-12T08:45:30.881+0000] {processor.py:186} INFO - Started process (PID=465) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:45:30.883+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:45:30.889+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:45:30.888+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:45:30.914+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:45:30.909+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:45:30.915+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:45:31.216+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.352 seconds
[2025-05-12T08:46:01.798+0000] {processor.py:186} INFO - Started process (PID=476) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:46:01.800+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:46:01.805+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:46:01.804+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:46:01.826+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:46:01.821+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:46:01.827+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:46:01.971+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.185 seconds
[2025-05-12T08:46:33.012+0000] {processor.py:186} INFO - Started process (PID=488) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:46:33.013+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:46:33.018+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:46:33.017+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:46:33.040+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:46:33.035+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:46:33.041+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:46:33.123+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.122 seconds
[2025-05-12T08:47:04.071+0000] {processor.py:186} INFO - Started process (PID=498) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:47:04.076+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:47:04.081+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:47:04.080+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:47:04.120+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:47:04.115+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:47:04.122+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:47:04.180+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.125 seconds
[2025-05-12T08:47:34.627+0000] {processor.py:186} INFO - Started process (PID=508) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:47:34.629+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:47:34.633+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:47:34.633+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:47:34.655+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:47:34.650+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:47:34.657+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:47:34.737+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.122 seconds
[2025-05-12T08:48:05.249+0000] {processor.py:186} INFO - Started process (PID=519) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:48:05.254+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T08:48:05.259+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:48:05.258+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:48:05.280+0000] {logging_mixin.py:190} INFO - [2025-05-12T08:48:05.275+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T08:48:05.282+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T08:48:05.334+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.097 seconds
[2025-05-12T14:27:14.159+0000] {processor.py:186} INFO - Started process (PID=196) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T14:27:14.165+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T14:27:14.172+0000] {logging_mixin.py:190} INFO - [2025-05-12T14:27:14.171+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T14:27:14.215+0000] {logging_mixin.py:190} INFO - [2025-05-12T14:27:14.197+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T14:27:14.217+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T14:27:14.305+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.163 seconds
[2025-05-12T14:27:44.537+0000] {processor.py:186} INFO - Started process (PID=207) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T14:27:44.540+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T14:27:44.545+0000] {logging_mixin.py:190} INFO - [2025-05-12T14:27:44.544+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T14:27:44.568+0000] {logging_mixin.py:190} INFO - [2025-05-12T14:27:44.564+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T14:27:44.570+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T14:27:45.551+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 1.156 seconds
[2025-05-12T14:28:16.026+0000] {processor.py:186} INFO - Started process (PID=217) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T14:28:16.029+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T14:28:16.036+0000] {logging_mixin.py:190} INFO - [2025-05-12T14:28:16.036+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T14:28:16.085+0000] {logging_mixin.py:190} INFO - [2025-05-12T14:28:16.080+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T14:28:16.087+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T14:28:16.210+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.207 seconds
[2025-05-12T14:28:46.711+0000] {processor.py:186} INFO - Started process (PID=228) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T14:28:46.716+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-12T14:28:46.722+0000] {logging_mixin.py:190} INFO - [2025-05-12T14:28:46.721+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T14:28:46.747+0000] {logging_mixin.py:190} INFO - [2025-05-12T14:28:46.742+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-12T14:28:46.748+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-12T14:28:46.819+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.121 seconds
