[2025-05-11T13:48:51.109+0000] {processor.py:186} INFO - Started process (PID=200) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:48:51.110+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T13:48:51.115+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:48:51.114+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:48:51.297+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:48:51.236+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T13:48:51.299+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:48:51.561+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.463 seconds
[2025-05-11T13:49:22.584+0000] {processor.py:186} INFO - Started process (PID=210) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:49:22.591+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T13:49:22.607+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:49:22.603+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:49:22.700+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:49:22.683+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T13:49:22.707+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:49:22.871+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.361 seconds
[2025-05-11T13:49:53.291+0000] {processor.py:186} INFO - Started process (PID=222) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:49:53.294+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T13:49:53.299+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:49:53.299+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:49:53.331+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:49:53.318+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T13:49:53.334+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:49:53.470+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.199 seconds
[2025-05-11T13:54:44.185+0000] {processor.py:186} INFO - Started process (PID=197) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:54:44.189+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T13:54:44.201+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:54:44.198+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:54:44.292+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:54:44.267+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T13:54:44.295+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:54:44.542+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.397 seconds
[2025-05-11T13:55:15.674+0000] {processor.py:186} INFO - Started process (PID=208) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:55:15.674+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T13:55:15.679+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:55:15.679+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:55:15.786+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:55:15.778+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T13:55:15.788+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:55:16.398+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.737 seconds
[2025-05-11T13:55:47.289+0000] {processor.py:186} INFO - Started process (PID=220) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:55:47.293+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T13:55:47.307+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:55:47.306+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:55:47.347+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:55:47.327+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T13:55:47.357+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:55:47.415+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.140 seconds
[2025-05-11T13:56:18.194+0000] {processor.py:186} INFO - Started process (PID=231) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:56:18.196+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T13:56:18.201+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:56:18.201+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:56:18.224+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:56:18.219+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T13:56:18.225+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:56:18.279+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.098 seconds
[2025-05-11T13:56:49.278+0000] {processor.py:186} INFO - Started process (PID=242) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:56:49.281+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T13:56:49.287+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:56:49.287+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:56:49.311+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:56:49.306+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T13:56:49.313+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:56:49.574+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.310 seconds
[2025-05-11T13:57:19.759+0000] {processor.py:186} INFO - Started process (PID=253) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:57:19.761+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T13:57:19.767+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:57:19.766+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:57:19.792+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:57:19.786+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T13:57:19.793+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:57:19.851+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.105 seconds
[2025-05-11T13:57:50.265+0000] {processor.py:186} INFO - Started process (PID=264) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:57:50.267+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T13:57:50.292+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:57:50.291+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:57:50.323+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:57:50.318+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T13:57:50.325+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:57:50.381+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.128 seconds
[2025-05-11T13:58:21.367+0000] {processor.py:186} INFO - Started process (PID=275) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:58:21.370+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T13:58:21.374+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:58:21.374+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:58:21.394+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:58:21.390+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T13:58:21.396+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:58:21.457+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.102 seconds
[2025-05-11T13:58:51.687+0000] {processor.py:186} INFO - Started process (PID=285) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:58:51.688+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T13:58:51.694+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:58:51.694+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:58:51.717+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:58:51.712+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T13:58:51.719+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:58:51.907+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.233 seconds
[2025-05-11T13:59:22.163+0000] {processor.py:186} INFO - Started process (PID=296) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:59:22.170+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T13:59:22.187+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:59:22.184+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:59:22.214+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:59:22.209+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T13:59:22.215+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:59:22.381+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.229 seconds
[2025-05-11T13:59:52.589+0000] {processor.py:186} INFO - Started process (PID=307) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:59:52.631+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T13:59:52.637+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:59:52.636+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:59:52.663+0000] {logging_mixin.py:190} INFO - [2025-05-11T13:59:52.659+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T13:59:52.665+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T13:59:53.001+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.424 seconds
[2025-05-11T14:00:24.030+0000] {processor.py:186} INFO - Started process (PID=318) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:00:24.031+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:00:24.037+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:00:24.037+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:00:24.065+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:00:24.058+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:00:24.067+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:00:24.203+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.189 seconds
[2025-05-11T14:00:55.136+0000] {processor.py:186} INFO - Started process (PID=329) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:00:55.139+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:00:55.149+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:00:55.149+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:00:55.177+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:00:55.171+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:00:55.178+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:00:55.249+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.128 seconds
[2025-05-11T14:01:25.785+0000] {processor.py:186} INFO - Started process (PID=340) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:01:25.788+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:01:25.796+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:01:25.795+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:01:25.837+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:01:25.827+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:01:25.839+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:01:25.896+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.128 seconds
[2025-05-11T14:01:57.071+0000] {processor.py:186} INFO - Started process (PID=351) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:01:57.073+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:01:57.078+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:01:57.078+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:01:57.103+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:01:57.097+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:01:57.105+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:01:57.162+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.104 seconds
[2025-05-11T14:02:27.802+0000] {processor.py:186} INFO - Started process (PID=361) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:02:27.805+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:02:27.810+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:02:27.809+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:02:27.832+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:02:27.827+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:02:27.833+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:02:27.888+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.097 seconds
[2025-05-11T14:02:58.866+0000] {processor.py:186} INFO - Started process (PID=372) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:02:58.867+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:02:58.871+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:02:58.871+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:02:58.896+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:02:58.889+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:02:58.898+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:02:58.955+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.100 seconds
[2025-05-11T14:03:29.914+0000] {processor.py:186} INFO - Started process (PID=383) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:03:29.917+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:03:29.924+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:03:29.923+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:03:29.947+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:03:29.942+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:03:29.948+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:03:30.043+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.146 seconds
[2025-05-11T14:04:00.777+0000] {processor.py:186} INFO - Started process (PID=394) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:04:00.782+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:04:00.786+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:04:00.785+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:04:00.814+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:04:00.809+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:04:00.815+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:04:00.872+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.107 seconds
[2025-05-11T14:04:31.110+0000] {processor.py:186} INFO - Started process (PID=405) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:04:31.227+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:04:31.240+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:04:31.239+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:04:31.270+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:04:31.263+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:04:31.272+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:04:31.638+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.551 seconds
[2025-05-11T14:05:02.080+0000] {processor.py:186} INFO - Started process (PID=415) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:05:02.082+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:05:02.087+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:05:02.086+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:05:02.109+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:05:02.104+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:05:02.110+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:05:02.247+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.180 seconds
[2025-05-11T14:05:32.720+0000] {processor.py:186} INFO - Started process (PID=426) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:05:32.727+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:05:32.735+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:05:32.734+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:05:32.772+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:05:32.759+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:05:32.774+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:05:32.900+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.210 seconds
[2025-05-11T14:06:03.185+0000] {processor.py:186} INFO - Started process (PID=436) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:06:03.189+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:06:03.194+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:06:03.193+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:06:03.327+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:06:03.320+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:06:03.329+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:06:03.620+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.510 seconds
[2025-05-11T14:06:34.747+0000] {processor.py:186} INFO - Started process (PID=446) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:06:34.750+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:06:34.760+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:06:34.760+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:06:34.781+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:06:34.776+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:06:34.782+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:06:34.839+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.104 seconds
[2025-05-11T14:07:05.989+0000] {processor.py:186} INFO - Started process (PID=457) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:07:05.991+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:07:05.996+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:07:05.995+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:07:06.017+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:07:06.013+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:07:06.019+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:07:06.347+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.418 seconds
[2025-05-11T14:07:36.846+0000] {processor.py:186} INFO - Started process (PID=469) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:07:36.849+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:07:36.854+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:07:36.853+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:07:36.875+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:07:36.870+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:07:36.876+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:07:36.978+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.146 seconds
[2025-05-11T14:08:07.111+0000] {processor.py:186} INFO - Started process (PID=480) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:08:07.113+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:08:07.119+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:08:07.118+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:08:07.143+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:08:07.137+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:08:07.144+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:08:07.208+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.113 seconds
[2025-05-11T14:08:37.577+0000] {processor.py:186} INFO - Started process (PID=491) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:08:37.579+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:08:37.586+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:08:37.585+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:08:37.608+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:08:37.604+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:08:37.609+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:08:37.656+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.091 seconds
[2025-05-11T14:09:08.716+0000] {processor.py:186} INFO - Started process (PID=502) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:09:08.719+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:09:08.726+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:09:08.725+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:09:08.750+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:09:08.746+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:09:08.752+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:09:08.805+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.103 seconds
[2025-05-11T14:09:38.993+0000] {processor.py:186} INFO - Started process (PID=513) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:09:38.997+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:09:39.003+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:09:39.002+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:09:39.038+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:09:39.029+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:09:39.041+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:09:39.123+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.148 seconds
[2025-05-11T14:10:09.971+0000] {processor.py:186} INFO - Started process (PID=524) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:10:09.976+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:10:09.985+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:10:09.984+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:10:10.029+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:10:10.023+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:10:10.031+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:10:10.202+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.251 seconds
[2025-05-11T14:10:40.892+0000] {processor.py:186} INFO - Started process (PID=535) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:10:40.920+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:10:40.942+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:10:40.939+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:10:41.019+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:10:41.008+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:10:41.021+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:10:41.196+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.385 seconds
[2025-05-11T14:11:12.028+0000] {processor.py:186} INFO - Started process (PID=546) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:11:12.032+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:11:12.055+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:11:12.053+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:11:12.095+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:11:12.089+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:11:12.096+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:11:12.156+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.156 seconds
[2025-05-11T14:11:43.192+0000] {processor.py:186} INFO - Started process (PID=558) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:11:43.311+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:11:43.321+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:11:43.319+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:11:43.350+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:11:43.346+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:11:43.352+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:11:43.801+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.622 seconds
[2025-05-11T14:12:14.729+0000] {processor.py:186} INFO - Started process (PID=569) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:12:14.731+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:12:14.742+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:12:14.741+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:12:14.769+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:12:14.760+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:12:14.771+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:12:14.829+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.114 seconds
[2025-05-11T14:12:45.722+0000] {processor.py:186} INFO - Started process (PID=580) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:12:45.728+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:12:45.735+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:12:45.734+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:12:45.762+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:12:45.757+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:12:45.763+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:12:45.818+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.113 seconds
[2025-05-11T14:13:16.719+0000] {processor.py:186} INFO - Started process (PID=591) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:13:16.725+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:13:16.742+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:13:16.739+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:13:16.796+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:13:16.783+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:13:16.799+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:13:16.943+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.251 seconds
[2025-05-11T14:13:48.313+0000] {processor.py:186} INFO - Started process (PID=602) to work on /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:13:48.315+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/yellowtripdata_dag.py for tasks to queue
[2025-05-11T14:13:48.320+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:13:48.319+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:13:48.344+0000] {logging_mixin.py:190} INFO - [2025-05-11T14:13:48.339+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/yellowtripdata_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 41, in <module>
    yellowtripdata_dag()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/yellowtripdata_dag.py", line 30, in yellowtripdata_dag
    yellowtripdata_analytics = DbtTaskGroup(
                               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 256, in __init__
    project_config.validate_project()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 263, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /opt/airflow/dbt/dev/dbt_project.yml
[2025-05-11T14:13:48.345+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/yellowtripdata_dag.py
[2025-05-11T14:13:48.583+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/yellowtripdata_dag.py took 0.281 seconds
